[build.environment]
  NODE_VERSION = "18.17.1"

[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
